import streamlit as st
import pandas as pd

st.set_page_config(page_title="ILGA Bill Tracker", layout="wide")

st.title("🏛️ Illinois General Assembly Bill Tracker")
st.markdown("This dashboard tracks target bills and automatically updates daily.")

try:
    # Read the data generated by the background script
    df = pd.read_csv("bills_data.csv")
    
    # Render it as an interactive table
    st.dataframe(
        df,
        column_config={
            "LegiScan Link": st.column_config.LinkColumn("View on LegiScan")
        },
        hide_index=True,
        use_container_width=True
    )
except FileNotFoundError:
    st.warning("Data file not found. Wait for the background script to run or trigger it manually.")
